site_name: Research Workflow
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Applications: applications.md
  - Installation: 
    - Packaged Installation: installation.md
    - Manual Downloads: man_downloads.md
  - Templates: templates.md